# Generated by Django 5.0.2 on 2024-02-09 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='City',
            new_name='city',
        ),
    ]
